version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/nina-indexer
    overwrite: yes
hooks:
  BeforeInstall:
   - location: stop.sh
     timeout: 300
     runas: ec2-user
  AfterInstall:
   - location: setup.sh
     timeout: 300
     runas: ec2-user
  ApplicationStart:
   - location: run.sh --only nina-api
     timeout: 300
     runas: ec2-user
