version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/nina-indexer
    overwrite: yes
hooks:
  BeforeInstall:
   - location: scripts/stop.sh
     timeout: 300
     runas: ec2-user
  AfterInstall:
   - location: scripts/setup.sh
     timeout: 300
     runas: ec2-user
  ApplicationStart:
   - location: scripts/run.sh
     timeout: 300
     runas: ec2-user
